### PR TITLE
Add support for Firefox

### PR DESCRIPTION
**Pull request by prplecake**

### CODE REVIEW

**Comment by lrq3000** [comment]
Thank you very much @prplecake for your PRs. What  do you think remains to be done for the PR to be completed?

**Comment by prplecake** [comment]
The Firefox profile lookup needs to be more robust since [`.default-release`](https://github.com/barrettfdavis/online_actogram/pull/7/files#diff-8bc36d446ce9f95789a51442ee06da1ac3c06ed66d10d33213e33502fab9b2f2R108) isn't the only suffix used, and there could be multiple profiles available. In fact, the `*.default-release` profile isn't the default profile on one of my systems.

image

Since more data would be better for creating an accurate actogram, it might be desirable to read each profile's `places.sqlite`. I have an idea of how this could be done, I just haven't had the time to do so.

**Comment by lrq3000** [comment]
@prplecake Awesome, thank you very much for taking the time to reply! I am maintaining an official fork of this repo on Circadiaware as you saw in the other PR, and supporting Firefox was on our TODO so if you can complete it, I'll merge it asap :-)

Also I take this opportunity to ask you if by any chance you know how ActivityWatch on Android works? I mean, how does it fetch usage data? Indeed, I saw you contributed to ActivityWatch, and I noticed the other day when I installed AW on Android for the first time that it retroactively fetched usage data for several weeks prior to the install, which I find very surprising, but the same process can maybe be used to implement online_actogram's support for Android!

**Comment by prplecake** [comment]
> Also I take this opportunity to ask you if by any chance you know how ActivityWatch on Android works? I mean, how does it fetch usage data? Indeed, I saw you contributed to ActivityWatch, and I noticed the other day when I installed AW on Android for the first time that it retroactively fetched usage data for several weeks prior to the install, which I find very surprising, but the same process can maybe be used to implement online_actogram's support for Android!

I don't, no. I don't do any Android development, and I haven't used AW in several months now.

**Comment by lrq3000** [comment]
@prplecake I'd like to merge in your draft PR in the official fork on Circadiaware and implement your suggested improvement. You mentioned you had an idea to implement an accurate detection of the currently used profile in Firefox, if you lack time to implement it, you can tell me your idea and I will work on it over your draft PR :-)

**Comment by prplecake** [comment]
Closing in favor of https://github.com/Circadiaware/online_actogram/pull/3

**Pull request closed without merging**
